"""001_initial_all_tables

Revision ID: a5ebdb24b422
Revises: 
Create Date: 2026-07-02 21:05:26.271203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ebdb24b422'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=True)
    op.create_table('alerts',
    sa.Column('event_id', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('elder_name', sa.String(length=50), nullable=False),
    sa.Column('elder_id', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('create_time', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('ai_diagnosis', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('action_type', sa.String(length=20), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.String(length=20), nullable=False),
    sa.Column('record_date', sa.String(length=10), nullable=True),
    sa.Column('calls_today', sa.Integer(), nullable=True),
    sa.Column('api_calls_today', sa.Integer(), nullable=True),
    sa.Column('tokens_today', sa.Integer(), nullable=True),
    sa.Column('tokens_week', sa.Integer(), nullable=True),
    sa.Column('tokens_month', sa.Integer(), nullable=True),
    sa.Column('limit_daily', sa.Integer(), nullable=True),
    sa.Column('monthly_limit', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('device_sn', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('mac', sa.String(length=50), nullable=False),
    sa.Column('village_name', sa.String(length=50), nullable=True),
    sa.Column('bind_elder', sa.String(length=50), nullable=True),
    sa.Column('bind_elder_id', sa.String(length=20), nullable=True),
    sa.Column('is_online', sa.Integer(), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('signal', sa.String(length=30), nullable=True),
    sa.Column('last_active', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.String(length=30), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('device_sn'),
    sa.UniqueConstraint('mac')
    )
    op.create_table('door_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('elder_id', sa.String(length=20), nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=10), nullable=False),
    sa.Column('event_time', sa.String(length=30), nullable=False),
    sa.Column('event_date', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_door_events_elder_id'), 'door_events', ['elder_id'], unique=False)
    op.create_table('elders',
    sa.Column('elder_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=4), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('device_sn', sa.String(length=30), nullable=True),
    sa.Column('gateway_sn', sa.String(length=30), nullable=True),
    sa.Column('emergency_contact', sa.String(length=20), nullable=True),
    sa.Column('emergency_relation', sa.String(length=100), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.Column('bind_duration', sa.String(length=50), nullable=True),
    sa.Column('risk_tags', sa.Text(), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.Column('recent_activities', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('elder_id')
    )
    op.create_table('health_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('elder_id', sa.String(length=20), nullable=False),
    sa.Column('report_month', sa.String(length=7), nullable=False),
    sa.Column('risk_tags', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('data_source', sa.String(length=200), nullable=True),
    sa.Column('generated_by', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_reports_elder_id'), 'health_reports', ['elder_id'], unique=False)
    op.create_table('towns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('visit_tasks',
    sa.Column('task_id', sa.String(length=20), nullable=False),
    sa.Column('elder_name', sa.String(length=50), nullable=False),
    sa.Column('elder_id', sa.String(length=20), nullable=True),
    sa.Column('trigger_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('create_time', sa.String(length=30), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('village_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('villages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('town_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['town_id'], ['towns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('villages')
    op.drop_table('visit_tasks')
    op.drop_table('towns')
    op.drop_index(op.f('ix_health_reports_elder_id'), table_name='health_reports')
    op.drop_table('health_reports')
    op.drop_table('elders')
    op.drop_index(op.f('ix_door_events_elder_id'), table_name='door_events')
    op.drop_table('door_events')
    op.drop_table('devices')
    op.drop_table('api_usage')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
